const missions=[
{z:"01 · ESTRUCTURA",t:"La sala vacía",story:"La primera sala perdió el esqueleto del documento.",lesson:"Un documento HTML comienza con <code>&lt;!DOCTYPE html&gt;</code>. Dentro de <code>&lt;html&gt;</code> se organizan <code>&lt;head&gt;</code> y <code>&lt;body&gt;</code>.",task:"Creá un documento completo con <b>DOCTYPE</b>, <code>&lt;html lang=\"es\"&gt;</code>, <code>&lt;head&gt;</code>, <code>&lt;meta charset=\"UTF-8\"&gt;</code>, un <code>&lt;title&gt;</code> con texto y un <code>&lt;body&gt;</code> que contenga el párrafo <b>Sala restaurada</b>.",starter:"<!-- Reconstruí el documento -->",check:(d,s)=>[/^\s*<!doctype html>/i.test(s),d.documentElement.lang==="es",!!d.head.querySelector('meta[charset="UTF-8" i]'),!!d.title.trim(),[...d.body.querySelectorAll("p")].some(p=>p.textContent.trim()==="Sala restaurada")]},
{z:"02 · ENCABEZADOS",t:"Carteles de la exposición",story:"Los títulos de las salas perdieron su jerarquía.",lesson:"Los encabezados van de <code>&lt;h1&gt;</code> a <code>&lt;h6&gt;</code>. <code>&lt;h1&gt;</code> representa el encabezado principal; los demás organizan niveles inferiores.",task:"Creá un <code>&lt;h1&gt;</code> que diga <b>Museo Digital</b> y debajo un <code>&lt;h2&gt;</code> que diga <b>Colección 2026</b>.",starter:"",check:d=>d.querySelector("h1")?.textContent.trim()==="Museo Digital"&&d.querySelector("h2")?.textContent.trim()==="Colección 2026"},
{z:"03 · PÁRRAFOS",t:"Ficha recuperada",story:"Una ficha apareció como un bloque ilegible.",lesson:"<code>&lt;p&gt;</code> crea párrafos, <code>&lt;br&gt;</code> fuerza un salto de línea y <code>&lt;hr&gt;</code> marca una separación temática.",task:"Creá un párrafo con el texto <b>Archivo recuperado</b>, agregá un <code>&lt;br&gt;</code> y luego un <code>&lt;hr&gt;</code>.",starter:"",check:d=>[...d.querySelectorAll("p")].some(p=>p.textContent.includes("Archivo recuperado")&&p.querySelector("br"))&&!!d.querySelector("hr")},
{z:"04 · ÉNFASIS",t:"Mensaje destacado",story:"El sistema necesita distinguir información importante.",lesson:"<code>&lt;strong&gt;</code> indica importancia y <code>&lt;em&gt;</code> énfasis. <code>&lt;mark&gt;</code> resalta y <code>&lt;small&gt;</code> representa texto secundario.",task:"Escribí un párrafo que contenga <code>&lt;strong&gt;Importante&lt;/strong&gt;</code> y <code>&lt;em&gt;revisar la colección&lt;/em&gt;</code>.",starter:"<p>\n  \n</p>",check:d=>d.querySelector("p strong")?.textContent.trim()==="Importante"&&d.querySelector("p em")?.textContent.trim()==="revisar la colección"},
{z:"05 · LISTA UL",t:"Inventario de piezas",story:"Tres piezas necesitan volver al inventario.",lesson:"<code>&lt;ul&gt;</code> crea una lista no ordenada. Cada elemento se escribe con <code>&lt;li&gt;</code>.",task:"Creá una lista <code>&lt;ul&gt;</code> con exactamente tres elementos: <b>Fotografía</b>, <b>Mapa</b> y <b>Audio</b>.",starter:"",check:d=>{let x=[...d.querySelectorAll("ul>li")].map(e=>e.textContent.trim());return x.length===3&&x.join("|")==="Fotografía|Mapa|Audio"}},
{z:"06 · LISTA OL",t:"Ruta de restauración",story:"El equipo necesita seguir los pasos en orden.",lesson:"<code>&lt;ol&gt;</code> crea una lista numerada automáticamente. Sus elementos también se escriben con <code>&lt;li&gt;</code>.",task:"Creá una lista ordenada con tres pasos: <b>Abrir archivo</b>, <b>Revisar etiquetas</b> y <b>Guardar cambios</b>.",starter:"",check:d=>{let x=[...d.querySelectorAll("ol>li")].map(e=>e.textContent.trim());return x.length===3&&x.join("|")==="Abrir archivo|Revisar etiquetas|Guardar cambios"}},
{z:"07 · ENLACES",t:"Pasarela externa",story:"La exposición perdió su salida hacia otro recurso.",lesson:"La etiqueta <code>&lt;a&gt;</code> crea enlaces. <code>href</code> indica el destino y <code>target=\"_blank\"</code> permite abrirlo en una pestaña nueva.",task:"Creá un enlace con texto <b>Visitar recurso</b>, <code>href=\"https://example.com\"</code> y <code>target=\"_blank\"</code>.",starter:"",check:d=>{let a=d.querySelector("a");return a&&a.textContent.trim()==="Visitar recurso"&&a.getAttribute("href")==="https://example.com"&&a.getAttribute("target")==="_blank"}},
{z:"08 · IMÁGENES",t:"Retrato perdido",story:"La ficha de una obra conserva el marco, pero no su descripción.",lesson:"<code>&lt;img&gt;</code> utiliza <code>src</code> para indicar la imagen y <code>alt</code> para proporcionar texto alternativo.",task:"Insertá una imagen con <code>src=\"museo.jpg\"</code> y <code>alt=\"Entrada del museo\"</code>.",starter:"",check:d=>{let i=d.querySelector("img");return i&&i.getAttribute("src")==="museo.jpg"&&i.getAttribute("alt")==="Entrada del museo"}},
{z:"09 · MULTIMEDIA",t:"Archivo sonoro",story:"Una grabación histórica está lista para volver a reproducirse.",lesson:"<code>&lt;audio&gt;</code> y <code>&lt;video&gt;</code> permiten incorporar multimedia. El atributo <code>controls</code> muestra los controles de reproducción.",task:"Creá un elemento <code>&lt;audio&gt;</code> con <code>src=\"relato.mp3\"</code> y el atributo <code>controls</code>.",starter:"",check:d=>{let a=d.querySelector("audio");return a&&a.getAttribute("src")==="relato.mp3"&&a.hasAttribute("controls")}},
{z:"10 · FINAL",t:"Reapertura del museo",story:"Todas las salas responden. Falta reconstruir la portada.",lesson:"Combiná la estructura y las etiquetas practicadas. La jerarquía y los atributos deben ser correctos.",task:"Creá un documento completo con <code>lang=\"es\"</code>, <code>meta charset=\"UTF-8\"</code>, título de pestaña <b>Museo Nexo</b>, un <code>&lt;h1&gt;</code> que diga <b>Museo Nexo</b>, un párrafo que incluya <code>&lt;strong&gt;</code> o <code>&lt;em&gt;</code>, una lista <code>&lt;ul&gt;</code> con al menos 3 <code>&lt;li&gt;</code>, un enlace con <code>href</code>, una imagen con <code>src</code> y <code>alt</code>, y un elemento <code>&lt;audio&gt;</code> con <code>src</code> y <code>controls</code>.",starter:"<!-- Desafío final: escribí el documento completo -->",check:(d,s)=>/^\s*<!doctype html>/i.test(s)&&d.documentElement.lang==="es"&&!!d.head.querySelector('meta[charset="UTF-8" i]')&&d.title==="Museo Nexo"&&d.querySelector("h1")?.textContent.trim()==="Museo Nexo"&&!!d.querySelector("p")&&!!d.querySelector("p strong, p em")&&d.querySelectorAll("ul>li").length>=3&&!!d.querySelector("a[href]")&&!!d.querySelector("img[src][alt]")&&!!d.querySelector("audio[src][controls]")}
];
let cur=0, solved=new Set(), answers={}, failed={}, verified={}; const $=s=>document.querySelector(s);
function preview(){answers[cur]=$("#editor").value;$("#preview").srcdoc=answers[cur]}
function renderMap(){ $("#map").innerHTML=missions.map((m,i)=>`<button data-i="${i}" class="${i===cur?'active':''}" ${i>solved.size?'disabled':''}>${m.z}</button>`).join("");document.querySelectorAll("#map button").forEach(b=>b.onclick=()=>{cur=+b.dataset.i;render()})}
function render(){let m=missions[cur];$("#zone").textContent=m.z;$("#title").textContent=m.t;$("#story").textContent=m.story;$("#lesson").innerHTML=m.lesson;$("#task").innerHTML=m.task;$("#editor").value=answers[cur]??m.starter;$("#feedback").textContent=solved.has(cur)?"✓ Misión superada.":"";$("#feedback").className=solved.has(cur)?"ok":"";$("#prev").disabled=cur===0;$("#next").disabled=!solved.has(cur)||cur===9;renderMap();preview();status()}
function status(){let n=solved.size;$("#grade").textContent=`${n} / 10`;$("#done").textContent=`${n} / 10`}
function parse(src){let p=new DOMParser();return p.parseFromString(src,"text/html")}
$("#begin").onclick=()=>{if(!$("#student").value.trim()){alert("Ingresá nombre y apellido.");return}$("#start").classList.add("hidden");$("#app").classList.remove("hidden");render()}
$("#editor").oninput=()=>{preview();if(solved.has(cur)){solved.delete(cur);$("#next").disabled=true;status();renderMap()}}
$("#reset").onclick=()=>{$("#editor").value=missions[cur].starter;preview();$("#feedback").textContent=""}
$("#check").onclick=()=>{let src=$("#editor").value;answers[cur]=src;verified[cur]=(verified[cur]||0)+1;let ok=false;try{let d=parse(src),r=missions[cur].check(d,src);ok=Array.isArray(r)?r.every(Boolean):!!r}catch(e){}if(!ok){failed[cur]=(failed[cur]||0)+1;$("#feedback").className="bad";$("#feedback").textContent="✕ Todavía hay requisitos sin cumplir. Revisá la consigna. Intento incorrecto registrado.";document.querySelector(".mission").classList.remove("mission-ok");document.querySelector(".mission").classList.add("mission-error");setTimeout(()=>document.querySelector(".mission")?.classList.remove("mission-error"),650);return}solved.add(cur);$("#feedback").className="ok";$("#feedback").textContent="✓ MISIÓN RESTAURADA · Sumaste 1 punto.";document.querySelector(".mission").classList.remove("mission-error");document.querySelector(".mission").classList.add("mission-ok");setTimeout(()=>document.querySelector(".mission")?.classList.remove("mission-ok"),1200);$("#next").disabled=cur===9;status();renderMap()}
$("#prev").onclick=()=>{if(cur>0){cur--;render()}};$("#next").onclick=()=>{if(solved.has(cur)&&cur<9){cur++;render()}}
$("#pdf").onclick=()=>{let name=$("#student").value.trim();answers[cur]=$("#editor").value;const {jsPDF}=window.jspdf;let doc=new jsPDF({unit:"mm",format:"a4"}),y=18;doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text("ARCHIVO NEXO - Informe de HTML",15,y);y+=9;doc.setFontSize(10);doc.setFont("helvetica","normal");doc.text("Unidad Curricular: Páginas Webs",15,y);y+=6;doc.text("Docente: Gianna Giupponi",15,y);y+=6;doc.text(`Estudiante: ${name}`,15,y);y+=7;doc.setFont("helvetica","bold");doc.setFontSize(13);doc.text(`Calificacion: ${solved.size} / 10`,15,y);y+=9;missions.forEach((m,i)=>{if(y>255){doc.addPage();y=18}let code=(answers[i]||"").trim(),state=solved.has(i)?"SUPERADO":(!code?"SIN RESPUESTA":((verified[i]||0)?"NO SUPERADO":"NO VERIFICADO"));doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text(`${i+1}. ${m.t} - ${state} (1 pt)`,15,y);y+=5;doc.setFont("helvetica","normal");doc.setFontSize(8);doc.text(`Intentos incorrectos: ${failed[i]||0}`,15,y);y+=5;doc.setFont("courier","normal");let lines=doc.splitTextToSize(code||"(sin respuesta)",175);if(y+lines.length*3.6>280){doc.addPage();y=18}doc.text(lines,15,y);y+=lines.length*3.6+7});doc.save(`Archivo_Nexo_${name.replace(/\s+/g,"_")}.pdf`)}
