const M=[
{z:"01 · FORM",t:"Canal de ingreso",story:"La estación necesita recuperar el formulario base para recibir datos.",lesson:"<code>&lt;form&gt;</code> agrupa los controles. En esta misión usamos <code>action=\"#\"</code> y <code>method=\"post\"</code>.",task:"Creá un <code>&lt;form action=\"#\" method=\"post\"&gt;</code> que contenga un campo <code>input type=\"text\"</code>.",starter:"",check:d=>{let f=d.querySelector('form');return !!(f&&f.getAttribute('action')==="#"&&f.getAttribute('method')?.toLowerCase()==="post"&&f.querySelector('input[type="text"]'))}},
{z:"02 · LABEL",t:"Identidad del tripulante",story:"El sistema recibe datos, pero todavía no sabe qué representa cada campo.",lesson:"Usá <code>&lt;label for=\"nombre\"&gt;</code> y relacioná ese <code>for</code> con el <code>id</code> del input.",task:"Dentro de un formulario, creá un <code>label</code> con texto <b>Nombre</b> y <code>for=\"nombre\"</code>. Agregá un <code>input type=\"text\" id=\"nombre\" name=\"nombre\"</code>.",starter:"<form>\n\n</form>",check:d=>{let l=d.querySelector('form label[for="nombre"]'),i=d.querySelector('form input#nombre[name="nombre"][type="text"]');return !!(l&&l.textContent.trim()==="Nombre"&&i)}},
{z:"03 · TIPOS",t:"Datos de contacto",story:"El módulo de comunicaciones necesita distinguir correo y edad.",lesson:"HTML ofrece distintos tipos de <code>input</code>. <code>email</code> está pensado para correo y <code>number</code> para valores numéricos.",task:"Dentro de un formulario, creá un <code>input type=\"email\" name=\"correo\"</code> y un <code>input type=\"number\" name=\"edad\"</code>.",starter:"<form>\n\n</form>",check:d=>!!d.querySelector('form input[type="email"][name="correo"]')&&!!d.querySelector('form input[type="number"][name="edad"]')},
{z:"04 · OPCIONES",t:"Selección de turno",story:"Hay que asignar a cada operador/a un único turno.",lesson:"Los <code>radio</code> permiten elegir una opción de un grupo cuando comparten el mismo <code>name</code>.",task:"Creá dos opciones <code>radio</code> con <code>name=\"turno\"</code>. Una debe tener <code>value=\"dia\"</code> y otra <code>value=\"noche\"</code>.",starter:"<form>\n\n</form>",check:d=>{let r=[...d.querySelectorAll('form input[type="radio"][name="turno"]')];return r.length===2&&r.some(x=>x.value==="dia")&&r.some(x=>x.value==="noche")}},
{z:"05 · CHECKBOX",t:"Sistemas habilitados",story:"Un operador puede controlar más de un sistema al mismo tiempo.",lesson:"Los <code>checkbox</code> permiten seleccionar varias opciones independientes.",task:"Creá tres <code>checkbox</code> con <code>name=\"sistema\"</code> y valores <b>comunicacion</b>, <b>energia</b> y <b>navegacion</b>.",starter:"<form>\n\n</form>",check:d=>{let c=[...d.querySelectorAll('form input[type="checkbox"][name="sistema"]')].map(x=>x.value);return c.length===3&&["comunicacion","energia","navegacion"].every(v=>c.includes(v))}},
{z:"06 · SELECT",t:"Destino orbital",story:"La ruta debe elegirse desde una lista controlada de destinos.",lesson:"<code>&lt;select&gt;</code> contiene opciones <code>&lt;option&gt;</code>. El atributo <code>value</code> representa el dato enviado.",task:"Creá un <code>select name=\"destino\"</code> con tres <code>option</code> cuyos valores sean <b>luna</b>, <b>marte</b> y <b>europa</b>.",starter:"<form>\n\n</form>",check:d=>{let s=d.querySelector('form select[name="destino"]');if(!s)return false;let v=[...s.querySelectorAll('option')].map(o=>o.value);return ["luna","marte","europa"].every(x=>v.includes(x))}},
{z:"07 · TEXTAREA",t:"Mensaje de misión",story:"Falta un canal para enviar mensajes extensos y evitar transmisiones vacías.",lesson:"<code>&lt;textarea&gt;</code> sirve para texto de varias líneas. <code>required</code> obliga a completar un control antes del envío.",task:"Creá un <code>textarea name=\"mensaje\" required</code> y un botón <code>&lt;button type=\"submit\"&gt;Transmitir&lt;/button&gt;</code>.",starter:"<form>\n\n</form>",check:d=>{let t=d.querySelector('form textarea[name="mensaje"][required]'),b=d.querySelector('form button[type="submit"]');return !!(t&&b&&b.textContent.trim()==="Transmitir")}},
{z:"08 · FINAL",t:"Consola de transmisión",story:"Los siete módulos responden. Falta ensamblar la consola completa.",lesson:"Integrá lo practicado: formulario, etiquetas asociadas, tipos de input, opciones, selección, área de texto, validación y envío.",task:"Construí un <code>form method=\"post\"</code> que incluya: un label asociado a un campo de texto; un email <code>required</code>; al menos 2 radio con el mismo <code>name</code>; al menos 2 checkbox; un <code>select</code> con al menos 3 opciones; un <code>textarea required</code>; y un botón <code>submit</code>. Los textos y valores los elegís vos.",starter:"<!-- Consola final -->\n<form method=\"post\">\n\n</form>",check:d=>{let f=d.querySelector('form[method="post"]');if(!f)return false;let labels=[...f.querySelectorAll('label[for]')],linked=labels.some(l=>f.querySelector('#'+CSS.escape(l.getAttribute('for'))));let radios=[...f.querySelectorAll('input[type="radio"][name]')],same=radios.length>=2&&radios.some((r,i)=>radios.some((q,j)=>i!==j&&q.name===r.name));return linked&&!!f.querySelector('input[type="text"]')&&!!f.querySelector('input[type="email"][required]')&&same&&f.querySelectorAll('input[type="checkbox"]').length>=2&&f.querySelectorAll('select option').length>=3&&!!f.querySelector('textarea[required]')&&!!f.querySelector('button[type="submit"],input[type="submit"]')}}
];
let cur=0,solved=new Set(),answers={},fails={},checks={};const $=s=>document.querySelector(s);
function doc(src){return new DOMParser().parseFromString(src,"text/html")}
function points(){return Math.round(solved.size*1.25*100)/100}
function status(){$("#count").textContent=`${solved.size} / 8`;$("#score").textContent=`${points()} / 10`}
function map(){ $("#map").innerHTML=M.map((m,i)=>`<button data-i="${i}" class="${i===cur?'active':''}" ${i>solved.size?'disabled':''}>${String(i+1).padStart(2,'0')}</button>`).join("");document.querySelectorAll("#map button").forEach(b=>b.onclick=()=>{cur=+b.dataset.i;render()})}
function render(){let m=M[cur];$("#zone").textContent=m.z;$("#title").textContent=m.t;$("#story").textContent=m.story;$("#lesson").innerHTML=m.lesson;$("#task").innerHTML=m.task;$("#editor").value=answers[cur]??m.starter;$("#feedback").textContent=solved.has(cur)?"✓ MÓDULO RECUPERADO":"";$("#feedback").className=solved.has(cur)?"ok":"";$("#prev").disabled=cur===0;$("#next").disabled=!solved.has(cur)||cur===7;preview();map();status()}
function preview(){answers[cur]=$("#editor").value;$("#preview").srcdoc=answers[cur]}
$("#start").onclick=()=>{let n=$("#student").value.trim();if(!n)return alert("Ingresá tu nombre y apellido.");$("#who").textContent=n;$("#intro").classList.add("hidden");$("#app").classList.remove("hidden");render()}
$("#editor").oninput=()=>{preview();if(solved.has(cur)){solved.delete(cur);status();map();$("#next").disabled=true}}
$("#reset").onclick=()=>{$("#editor").value=M[cur].starter;preview();$("#feedback").textContent="";$("#feedback").className=""}
$("#check").onclick=()=>{let src=$("#editor").value;answers[cur]=src;checks[cur]=(checks[cur]||0)+1;let ok=false;try{ok=!!M[cur].check(doc(src),src)}catch(e){}let box=document.querySelector(".mission");box.classList.remove("good","error");if(!ok){fails[cur]=(fails[cur]||0)+1;$("#feedback").className="bad";$("#feedback").textContent="✕ CÓDIGO NO VALIDADO · Revisá todos los requisitos. Intento incorrecto registrado.";box.classList.add("error");setTimeout(()=>box.classList.remove("error"),700);return}solved.add(cur);$("#feedback").className="ok";$("#feedback").textContent="✓ MÓDULO RECUPERADO · +1,25 puntos";box.classList.add("good");setTimeout(()=>box.classList.remove("good"),900);$("#next").disabled=cur===7;status();map()}
$("#prev").onclick=()=>{if(cur){cur--;render()}};$("#next").onclick=()=>{if(solved.has(cur)&&cur<7){cur++;render()}}
$("#pdf").onclick=()=>{answers[cur]=$("#editor").value;const {jsPDF}=window.jspdf, p=new jsPDF({unit:"mm",format:"a4"});let y=17,n=$("#who").textContent;p.setFont("helvetica","bold");p.setFontSize(18);p.text("CENTRAL ORBITA - Informe de Formularios HTML",14,y);y+=8;p.setFontSize(10);p.setFont("helvetica","normal");p.text("Unidad Curricular: Paginas Webs",14,y);y+=5;p.text("Docente: Gianna Giupponi",14,y);y+=5;p.text(`Estudiante: ${n}`,14,y);y+=7;p.setFont("helvetica","bold");p.setFontSize(13);p.text(`Nota: ${points()} / 10`,14,y);y+=9;M.forEach((m,i)=>{if(y>255){p.addPage();y=17}let code=(answers[i]||"").trim(),st=solved.has(i)?"SUPERADO":(!code?"SIN RESPUESTA":((checks[i]||0)?"NO SUPERADO":"NO VERIFICADO"));p.setFont("helvetica","bold");p.setFontSize(10);p.text(`${i+1}. ${m.t} - ${st} (1,25 pts)`,14,y);y+=5;p.setFont("helvetica","normal");p.setFontSize(8);p.text(`Intentos incorrectos: ${fails[i]||0}`,14,y);y+=5;p.setFont("courier","normal");let lines=p.splitTextToSize(code||"(sin respuesta)",177);if(y+lines.length*3.4>280){p.addPage();y=17}p.text(lines,14,y);y+=lines.length*3.4+7});p.save(`Central_Orbita_${n.replace(/\s+/g,"_")}.pdf`)}
